Jenkinsfile.yml, README.md, build.gradle, demo/Dockerfile-rendezvous, demo/docker-compose.yml, src/test/java/org/sdo/rendezvous/controllers/ErrorMessageControllerTest.java, src/test/java/org/sdo/rendezvous/controllers/TransferOwnership0ControllerTest.java, src/test/java/org/sdo/rendezvous/crypto/HashGeneratorTest.java, src/test/java/org/sdo/rendezvous/crypto/TO1JWTokenFactoryTest.java, src/test/java/org/sdo/rendezvous/repositories/JedisRepositoryTest.java, src/test/java/org/sdo/rendezvous/services/EpidVerificationServiceTest.java, src/test/java/org/sdo/rendezvous/utils/ArrayByteBuilderTest.java
Added configurations for migrating the service to java 11
-Updated build script.
-Updated unit test annotation.
-Updated system requirements in README.
=> Updates for Java 11 enablement

Jenkinsfile.yml
Added archive artifacts step to jenkins file to pull the binaries of rendezvous-service in jenkins
Signed-off-by: Mareddy, Deepthi <deepthix.mareddy@intel.com>
=> Update jenkins file to archive the binaries of rendezvous-service in jenkins

demo/README.md, demo/docker-compose.yml
update demo/docker-compos.yaml to use correct header
Signed-off-by: Tom Barnes <thomas.j.barnes@intel.com>
=> Update demo readme files with -not for production- note

Jenkinsfile.yml
Added stage Run smoke test to run rendezvous-service with combination of other SDO components.
Signed-off-by: Mareddy, Deepthi <depthix.mareddy@intel.com>
=> Update jenkinsfile to run smoketest

pom.xml
- Updating dependencies to latest version
=> Version update for dependencies

src/main/java/org/sdo/rendezvous/authenticators/AuthenticatorFactory.java, src/main/java/org/sdo/rendezvous/authenticators/AuthenticatorOnDieEcdsaWithSha384.java, src/main/java/org/sdo/rendezvous/model/types/PkOnDieEcdsaEnc.java, src/main/java/org/sdo/rendezvous/model/types/PkOnDieEcdsaNull.java, src/main/java/org/sdo/rendezvous/model/types/PublicKeyEncoding.java, src/main/java/org/sdo/rendezvous/model/types/PublicKeyType.java, src/main/java/org/sdo/rendezvous/model/types/serialization/PkNullDeserializer.java, src/main/java/org/sdo/rendezvous/model/types/serialization/PkOnDieEcdsaNullDeserializer.java, src/main/java/org/sdo/rendezvous/model/types/serialization/PkOnDieEcdsaNullSerializer.java, src/main/java/org/sdo/rendezvous/model/types/serialization/PkX509EncDeserializer.java, src/main/java/org/sdo/rendezvous/model/types/serialization/ProveToSdoRequestDeserializer.java, src/main/java/org/sdo/rendezvous/model/types/serialization/PubKeyDeserializer.java, src/main/java/org/sdo/rendezvous/model/types/serialization/SigInfoDeserializer.java, src/main/java/org/sdo/rendezvous/services/TransferOwnership1Service.java, src/main/java/org/sdo/rendezvous/services/signature/OnDieEcdsaSignatureVerifier.java, src/main/java/org/sdo/rendezvous/services/signature/SignatureVerifier.java, src/test/java/org/sdo/rendezvous/authenticators/AuthenticatorFactoryTest.java, src/test/java/org/sdo/rendezvous/authenticators/AuthenticatorOnDieEcdsaWithSha384Test.java, src/test/java/org/sdo/rendezvous/model/types/PkOnDieEcdsaEncTest.java, src/test/java/org/sdo/rendezvous/model/types/PublicKeyEncodingTest.java, src/test/java/org/sdo/rendezvous/model/types/PublicKeyTypeTest.java, src/test/java/org/sdo/rendezvous/model/types/serialization/PkNullDeserializerTest.java, src/test/java/org/sdo/rendezvous/model/types/serialization/PkOnDieEcdsaNullDeserializerTest.java, src/test/java/org/sdo/rendezvous/model/types/serialization/PkOnDieEcdsaNullSerializerTest.java, src/test/java/org/sdo/rendezvous/services/TransferOwnership1ServiceTest.java, src/test/java/org/sdo/rendezvous/services/signature/OnDieEcdsaSignatureVerifierTest.java, src/test/java/org/sdo/rendezvous/services/signature/SignatureVerifierTest.java
- Enabling onprem RV for OnDie ECDSA Device.
=> Adding OnDie ECDSA Support

demo/README.md
=> Demo README update

demo/docker-compose.yml, pom.xml
- Updating version from 1.9 to 1.10
=> Version roll over

src/main/java/org/sdo/rendezvous/services/TransferOwnership1Service.java, src/test/java/org/sdo/rendezvous/services/TransferOwnership1ServiceTest.java
- Verifing AppId against a list of predefined values.
=> Adding verification check for AppId

README.md, demo/README.md
=> Update README file for formatting fixes

demo/cmdDocker.sh
=> Proxy fix for docker

demo/README.md
=> Updating instructions for adding allowlist and denylist credentials in redis docker.

pom.xml
Version roll to 1.10 release from 1.10-SNAPSHOT.
=> Roll Version to 1.10 Release

src/main/resources/application.properties
=> [Fix] Version roll over in application.properties

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Roll version for 1.10.1 development
=> Roll version for 1.10.1 development

build/Dockerfile, build/build.sh, pom.xml, src/main/resources/application.properties
Version roll-over to 1.10.1 Release.
=> Version roll-over to 1.10.1 Release

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
=> Prepare for 1.10.2 development

demo/cmdDocker.sh, demo/rendezvous.env, rendezvousService.sh
Update appropriate comments to inform the user to update the key
during deployment.
=> Update comments regarding test key generation

demo/Dockerfile-rendezvous
=> Update docker containers with latest packages

demo/Dockerfile-redis, demo/docker-compose.yml, demo/rendezvous.env, pom.xml, src/main/resources/application.properties
=> Roll version for 1.10.2 release

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover for 1.10.3 Development.
=> Version rollover for 1.10.3 Development

pom.xml
Upgrading to the latest spring-boot version.
spring-boot-starter:2.3.12.RELEASE => spring-boot-starter:2.5.4
=> Upgrading to the latest spring-boot version

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Roll version to 1.10.3 RELEASE.
=> Roll version to 1.10.3 RELEASE

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version roll over to 1.10.4-SNAPSHOT.
=> Version roll over to 1.10.4-SNAPSHOT

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover to 1.10.4 Release.
=> Version rollover to 1.10.4 Release

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover to 1.10.5-SNAPSHOT.
=> Version rollover to 1.10.5-SNAPSHOT

pom.xml, src/main/resources/application.properties
Version rollover to 1.10.5 Release.
=> Version rollover to 1.10.5 Release

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover to 1.10.6-SNAPSHOT.
=> Version rollover to 1.10.6-SNAPSHOT

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover to 1.10.6 Release.
=> Version rollover to 1.10.6 Release

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover to 1.10.7-SNAPSHOT.
=> Version rollover to 1.10.7-SNAPSHOT

Jenkinsfile.yml, pom.xml
Upgrading dependencies to latest version.
=> Upgrading dependencies to latest version

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version Rollover to 1.10.7 Release.
=> version rollover to 1.10.7 release

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover to 1.10.8 SNAPSHOT.
=> Version rollover to 1.10.8 SNAPSHOT

README.md, build/README.md, demo/README.md
Updating Docker version in README.
=> Updating Docker version in README

demo/docker-compose.yml, pom.xml, src/main/resources/application.properties
Version rollover to 1.10.8 Release.
=> Version rollover to 1.10.8 Release

pom.xml
=> Upgrading snakeYAML version

README.md
Updating EOL disclaimer in README
=> Updating EOL disclaimer in README
